### ISSUE TITLE
Big ServerInstances Bug on my server

### ISSUE THREAD

**Issue by HeyTV** [Sitrica/ServerInstances#8]
Hello. I recently purchased ServerInstances and I have configured Skungee and ServerInstances has been activated. The problem is that when I use the ServerInstances syntax in scripts, I get a big error that appears in my console. Here is : https://prnt.sc/10fmj7y & https://prnt.sc/10fmjg8

It's very annoying knowing that I paid for it... Can you please help me? Thank you in advance.

-HeyTV

**Comment by TheLimeGlass** [comment]
Duplicate of https://github.com/Skungee/ServerInstancesSkript/issues/25
